name: "ComfoBox MQTT Bridge"
slug: "comfobox_mqtt"
version: "1.0.4"
description: "Zehnder ComfoBox Series 5 (ELESTA) RS485/BACnet → MQTT Bridge"
startup: services
boot: true
init: false
build: .
hassio_api: false
homeassistant_api: false
arch:
  - aarch64
  - armv7
  - armhf
  - amd64

map:
  - config:rw

options:
  use_socat: true
  waveshare_host: ""
  waveshare_port: 0
  serial_port: "/tmp/comfobox"
  baudrate: 38400
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""

schema:
  use_socat: bool
  waveshare_host: str
  waveshare_port: int
  serial_port: str
  baudrate: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password
